// Wise Quotations
angular.module("app", []).controller("appCtrl", function($scope) {
  // define list of cars
  $scope.cars = [
    {
      make: "Dodge",
      color: "Blue",
      model: "Dakota"
    },
    {
      make: "Chevy",
      color: "Black",
      model: "Aveo"
    },
    {
      make: "Honda",
      color: "Black",
      model: "Accord"
    },
    {
      make: "Toyota",
      color: "Red",
      model: "Corolla"
    },
    {
      make: "Dodge",
      color: "Blue",
      model: "Stratus"
    },
    {
      make: "Toyota",
      color: "White",
      model: "Tacoma"
    },
    {
      make: "Ford",
      color: "Blue",
      model: "Focus"
    },
    {
      make: "GMC",
      color: "Red",
      model: "Sierra"
    },
    {
      make: "Dodge",
      color: "White",
      model: "Dakota"
    },
    {
      make: "Ford",
      color: "Black",
      model: "F150"
    }
  ];
   

  // define list of items
  $scope.quoteGroups = ["Humour", "Confidence", "Leadership"];
  $scope.carColors = ["Black", "Blue", "Red", "White"];
  
  // List of Quotations
  $scope.quotes = [
 {  "categ" :"Humour", "mynum" :"1",  "mysource" :"Bob Monkhouse", "myquote"  :"When I die, I want to go peacefully like my grandfather did–in his sleep. Not yelling and screaming like the passengers in his car." }, 
 {  "categ" :"Humour", "mynum" :"44",  "mysource" :"Sam Levenson", "myquote"  :"Insanity is hereditary. You get it from your children." }, 
 {  "categ" :"Humour", "mynum" :"43",  "mysource" :"John Wilmot - Earl of Rochester", "myquote"  :"Before I got married I had six theories about bringing up children.  Now I have six children and no theories." }, 
 {  "categ" :"Humour", "mynum" :"67",  "mysource" :"Anonymous", "myquote"  :"All my life I thought air was free, until I bought a bag of chips." }, 
 {  "categ" :"Humour", "mynum" :"35",  "mysource" :"Marilyn Monroe", "myquote"  :"Women who seek to be equal with men lack ambition." }, 
 {  "categ" :"Humour", "mynum" :"50",  "mysource" :"Wendy Liebman", "myquote"  :"My husband wanted one of those big screen TVs for his birthday. So I just moved his chair closer to the one we have already." }, 
 {  "categ" :"Humour", "mynum" :"26",  "mysource" :"Steven Wright", "myquote"  :"I couldn't repair your brakes, so I made your horn louder." }, 
 {  "categ" :"Humour", "mynum" :"60",  "mysource" :"Erma Bombeck", "myquote"  :"The odds of going to the store for a loaf of bread and coming out with only a loaf of bread are three billion to one." }, 
 {  "categ" :"Humour", "mynum" :"27",  "mysource" :"Anonymous", "myquote"  :"Children: You spend the first 2 years of their life teaching them to walk and talk. Then you spend the next 16 telling them to sit down and shut-up." }, 
 {  "categ" :"Humour", "mynum" :"47",  "mysource" :"Ben Bergor", "myquote"  :"It is amazing how quickly the kids learn to drive a car, yet are unable to understand the lawn mower, snowblower and vacuum cleaner." }, 
 {  "categ" :"Humour", "mynum" :"51",  "mysource" :"Jerry Seinfeld", "myquote"  :"According to most studies, people's number one fear is public speaking. Number two is death. Death is number two! Does that sound right? That means to the average person, if you go to a funeral, you're better off in the casket than doing the eulogy." }, 
 {  "categ" :"Humour", "mynum" :"24",  "mysource" :"Oscar Wilde", "myquote"  :"Some cause happiness wherever they go.  Others, whenever they go." }, 
 {  "categ" :"Humour", "mynum" :"45",  "mysource" :"Bob Hope", "myquote"  :"A bank is a place that will lend you money, if you can prove that you don't need it." }, 
 {  "categ" :"Humour", "mynum" :"11",  "mysource" :"Caroline Rhea", "myquote"  :"My favorite machine at the gym is the vending machine." }, 
 {  "categ" :"Humour", "mynum" :"16",  "mysource" :"Emo Philips", "myquote"  :"I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness." }, 
 {  "categ" :"Humour", "mynum" :"36",  "mysource" :"Norm Crosby", "myquote"  :"When you go into court you are putting your fate into the hands of twelve people who weren't smart enough to get out of jury duty." }, 
 {  "categ" :"Humour", "mynum" :"52",  "mysource" :"Agatha Christie", "myquote"  :"An archaeologist is the best husband a woman can have.  The older she gets the more interested he is in her." }, 
 {  "categ" :"Humour", "mynum" :"63",  "mysource" :"Bob Hope", "myquote"  :"I grew up with six brothers. That's how I learned to dance.  Waiting for the bathroom." }, 
 {  "categ" :"Humour", "mynum" :"15",  "mysource" :"Socrates", "myquote"  :"By all means, marry. If you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher." }, 
 {  "categ" :"Humour", "mynum" :"22",  "mysource" :"Flip Wilson", "myquote"  :"If you think nobody cares if you're alive, try missing a couple of car payments." }, 
 {  "categ" :"Humour", "mynum" :"54",  "mysource" :"Phyllis Diller", "myquote"  :"Housework can't kill you, but why take a chance?" }, 
 {  "categ" :"Humour", "mynum" :"23",  "mysource" :"Anonymous", "myquote"  :"How is it one careless match can start a forest fire, but it takes a whole box to start a campfire?" }, 
 {  "categ" :"Humour", "mynum" :"65",  "mysource" :"Ogden Nash", "myquote"  :"To keep your marriage brimming, with love in the loving cup, whenever you're wrong admit it.  Whenever you're right shut up." }, 
 {  "categ" :"Humour", "mynum" :"33",  "mysource" :"Milton Berle", "myquote"  :"If evolution really works, how come mothers only have two hands?" }, 
 {  "categ" :"Humour", "mynum" :"46",  "mysource" :"Ronald Reagan", "myquote"  :"Politics is supposed to be the second oldest profession. I have come to realize that it bears a very close resemblance to the first." }, 
 {  "categ" :"Humour", "mynum" :"28",  "mysource" :"Steven Wright", "myquote"  :"I intend to live forever. So far, so good." }, 
 {  "categ" :"Humour", "mynum" :"37",  "mysource" :"Isaac Asimov", "myquote"  :"Those people who think they know everything are a great annoyance to those of us who do." }, 
 {  "categ" :"Humour", "mynum" :"56",  "mysource" :"Evan Esar", "myquote"  :"The best time to give advice to your children is while they're still young enough to believe you know what you're talking about." }, 
 {  "categ" :"Humour", "mynum" :"12",  "mysource" :"Charles Lamb", "myquote"  :"I always arrive late at the office, but I make up for it by leaving early." }, 
 {  "categ" :"Humour", "mynum" :"17",  "mysource" :"Greg King", "myquote"  :"Do not argue with an idiot. He will drag you down to his level and beat you with experience." }, 
 {  "categ" :"Humour", "mynum" :"13",  "mysource" :"Miles Kington", "myquote"  :"Knowledge is knowing a tomato is a fruit.  Wisdom is not putting it in a fruit salad." }, 
 {  "categ" :"Humour", "mynum" :"62",  "mysource" :"Dorothy Parker", "myquote"  :"The best way to keep children home is to make the home a pleasant atmosphere . . . and let the air out of the tires." }, 
 {  "categ" :"Humour", "mynum" :"10",  "mysource" :"Albert Einstein", "myquote"  :"Two things are infinite, the universe and human stupidity, and I am not yet completely sure about the universe." }, 
 {  "categ" :"Humour", "mynum" :"7",  "mysource" :"Anonymous", "myquote"  :"Dogs have masters. Cats have staff." }, 
 {  "categ" :"Humour", "mynum" :"58",  "mysource" :"Jose Maria de Eca de Queiroz", "myquote"  :"Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason." }, 
 {  "categ" :"Humour", "mynum" :"30",  "mysource" :"Anonymous", "myquote"  :"Money can't buy happiness, but it sure makes misery easier to live with." }, 
 {  "categ" :"Humour", "mynum" :"32",  "mysource" :"Charles Wadsworth", "myquote"  :"By the time a man realizes that his father was right, he has a son who thinks he's wrong." }, 
 {  "categ" :"Humour", "mynum" :"3",  "mysource" :"Oscar Wilde", "myquote"  :"Always borrow money from a pessimist. He won't expect it back." }, 
 {  "categ" :"Humour", "mynum" :"53",  "mysource" :"Anonymous", "myquote"  :"The shinbone is a device for finding furniture in a dark room." }, 
 {  "categ" :"Humour", "mynum" :"25",  "mysource" :"Bill McGlashen", "myquote"  :"Patience is something you admire in the driver behind you, but not in one ahead." }, 
 {  "categ" :"Humour", "mynum" :"20",  "mysource" :"Dave Barry", "myquote"  :"Never, under any circumstances, take a sleeping pill and a laxative on the same night." }, 
 {  "categ" :"Humour", "mynum" :"59",  "mysource" :"George Jessel", "myquote"  :"The human brain is a wonderful thing. It starts working the moment you are born, and never stops until you stand up to speak in public." }, 
 {  "categ" :"Humour", "mynum" :"48",  "mysource" :"Bill Vaughan", "myquote"  :"We hope that, when the insects take over the world, they will remember with gratitude how we took them along on all our picnics." }, 
 {  "categ" :"Humour", "mynum" :"68",  "mysource" :"Anonymous", "myquote"  :"In the morning you beg to sleep more, in the afternoon you are dying to sleep, and at night you refuse to sleep." },
 {  "categ" :"Humour", "mynum" :"55",  "mysource" :"Will Rogers", "myquote"  :"All you need to grow fine, vigorous grass is a crack in your sidewalk." }, 
 {  "categ" :"Humour", "mynum" :"19",  "mysource" :"Henny Youngman", "myquote"  :"If at first you don't succeed . . . so much for skydiving." }, 
 {  "categ" :"Humour", "mynum" :"49",  "mysource" :"Anonymous", "myquote"  :"Evening News is where they begin with 'Good evening', and then proceed to tell you why it isn't." }, 
 {  "categ" :"Humour", "mynum" :"14",  "mysource" :"Douglas Adams", "myquote"  :"I love deadlines. I like the whooshing sound they make as they fly by." }, 
 {  "categ" :"Humour", "mynum" :"64",  "mysource" :"Muhammad Ali", "myquote"  :"If you even dream of beating me you'd better wake up and apologize." }, 
 {  "categ" :"Humour", "mynum" :"34",  "mysource" :"Anonymous", "myquote"  :"I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives." }, 
 {  "categ" :"Humour", "mynum" :"21",  "mysource" :"Wilson Mizner", "myquote"  :"If you steal from one author, it's plagiarism; if you steal from many, it's research." }, 
 {  "categ" :"Humour", "mynum" :"18",  "mysource" :"Franklin Jones", "myquote"  :"A bargain is something you don't need at a price you can't resist." }, 
 {  "categ" :"Humour", "mynum" :"39",  "mysource" :"Anonymous", "myquote"  :"When tempted to fight fire with fire, remember that the Fire Department usually uses water." }, 
 {  "categ" :"Humour", "mynum" :"5",  "mysource" :"Steve Martin", "myquote"  :"First the doctor told me the good news: I was going to have a disease named after me." }, 
 {  "categ" :"Humour", "mynum" :"29",  "mysource" :"Caskie Stinnett", "myquote"  :"A diplomat is someone who can tell you to go to hell in such a way that you will look forward to the trip." }, 
 {  "categ" :"Humour", "mynum" :"8",  "mysource" :"Rodney Dangerfield", "myquote"  :"I was such an ugly kid. When I played in the sandbox the cat kept trying to cover me up." }, 
 {  "categ" :"Humour", "mynum" :"66",  "mysource" :"Jerry Seinfeld", "myquote"  :"People who read the tabloids deserve to be lied to." }, 
 {  "categ" :"Humour", "mynum" :"57",  "mysource" :"Anonymous", "myquote"  :"Tell a man there are 300 billion stars in the universe and he'll believe you. Tell him a bench has wet paint on it and he'll have to touch it to be sure." }, 
 {  "categ" :"Humour", "mynum" :"40",  "mysource" :"Anonymous", "myquote"  :"To err is human, to blame it on somebody else shows management potential." }, 
 {  "categ" :"Humour", "mynum" :"4",  "mysource" :"Robert Bloch", "myquote"  :"Friendship is like peeing on yourself: everyone can see it, but only you get the warm feeling that it brings." }, 
 {  "categ" :"Humour", "mynum" :"69",  "mysource" :"Anonymous", "myquote"  :"Be nice to people on your way up, because you will need them on your way down." }, 
 {  "categ" :"Humour", "mynum" :"6",  "mysource" :"Dave Barry", "myquote"  :"My therapist told me the way to achieve true inner peace is to finish what I start. So far I've finished two bags of M&Ms and a chocolate cake. I feel better already." }, 
 {  "categ" :"Humour", "mynum" :"2",  "mysource" :"Elayne Boosler", "myquote"  :"I have six locks on my door all in a row. When I go out, I lock every other one. I figure no matter how long somebody stands there picking the locks, they are always locking three." }, 
 {  "categ" :"Humour", "mynum" :"61",  "mysource" :"Mark Twain", "myquote"  :"There is nothing so annoying as to have two people go right on talking when you're interrupting." }, 
 {  "categ" :"Humour", "mynum" :"31",  "mysource" :"Anonymous", "myquote"  :"Nothing sucks more than that moment during an argument when you realize you're wrong." }, 
 {  "categ" :"Humour", "mynum" :"38",  "mysource" :"Robert Frost", "myquote"  :"By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day." }, 
 {  "categ" :"Humour", "mynum" :"9",  "mysource" :"Anonymous", "myquote"  :"I have to exercise early in the morning before my brain figures out what I'm doing." }, 
 {  "categ" :"Humour", "mynum" :"41",  "mysource" :"Anonymous", "myquote"  :"I read recipes the same way I read science fiction. I get to the end and I think, 'Well, that's not going to happen.'" }, 
 {  "categ" :"Humour", "mynum" :"42",  "mysource" :"Franklin P. Jones", "myquote"  :"The trouble with being punctual is that nobody's there to appreciate it." },
 {  "categ" :"Confidence", "mynum" :"11",  "mysource" :"Ralph Waldo Emerson", "myquote"  :"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." },
 {  "categ" :"Confidence", "mynum" :"2",  "mysource" :"Nathaniel Branden", "myquote"  :"Tell me how a person judges his or her self esteem and I will tell you how that person operates at work, in love, in sex, in parenting, in every important aspect of existence – and how high he or she is likely to rise. The reputation you have with yourself – your self-esteem – is the single most important factor for a fulfilling life." },     
 {  "categ" :"Confidence", "mynum" :"3",  "mysource" :"Dale Carnegie", "myquote"  :"Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy." },     
 {  "categ" :"Confidence", "mynum" :"4",  "mysource" :"Orison Swett Marden", "myquote"  :"The golden opportunity you are seeking is in yourself. It is not in your environment, it is not in luck or chance, or the help of others.  It is in yourself alone." },     
 {  "categ" :"Confidence", "mynum" :"5",  "mysource" :"Aldous Leonard Huxley", "myquote"  :"There is only one corner of the universe you can be certain of improving, and that's your own self." },     
 {  "categ" :"Confidence", "mynum" :"6",  "mysource" :"Eleanor Roosevelt", "myquote"  :"No one can make you feel inferior without your consent." },     
 {  "categ" :"Confidence", "mynum" :"7",  "mysource" :"Katy Perry", "myquote"  :"If you're presenting yourself with confidence, you can pull off pretty much anything." },     
 {  "categ" :"Confidence", "mynum" :"8",  "mysource" :"Nathaniel Branden.", "myquote"  :"Of all the judgments we pass in life, none is more important than the judgment we pass on ourselves." },     
 {  "categ" :"Confidence", "mynum" :"9",  "mysource" :"Joe Namath", "myquote"  :"When you have confidence, you can have a lot of fun. And when you have fun, you can do amazing things." },     
 {  "categ" :"Confidence", "mynum" :"10",  "mysource" :"Sally Field", "myquote"  :"It took me a long time not to judge myself through someone else's eyes." },     
 {  "categ" :"Confidence", "mynum" :"1",  "mysource" :"Unknown", "myquote"  :"Always act like you're wearing an invisible crown." },  
 {  "categ" :"Confidence", "mynum" :"12",  "mysource" :"Marta Kagan", "myquote"  :"Listen to your heart above all other voices." },     
 {  "categ" :"Confidence", "mynum" :"13",  "mysource" :"Wayne Dyer", "myquote"  :"Self worth cannot be verified by others. You are worthy because you say it is so. If you depend on others for your value it is other-worth." },     
 {  "categ" :"Confidence", "mynum" :"14",  "mysource" :"T. Harv Eker", "myquote"  :"If you are insecure, guess what? The rest of the world is, too. Do not overestimate the competition and underestimate yourself. You are better than you think." },     
 {  "categ" :"Confidence", "mynum" :"15",  "mysource" :"William Jennings Bryan", "myquote"  :"The way to develop self-confidence is to do the thing you fear and get a record of successful experiences behind you." },     
 {  "categ" :"Confidence", "mynum" :"16",  "mysource" :"Michael Pitt ~ Delirious", "myquote"  :"It's a dead-end street if you sit around waiting for someone else to tell you you're okay." },     
 {  "categ" :"Confidence", "mynum" :"17",  "mysource" :"Christian Dior", "myquote"  :"Happiness is the secret to all beauty.  There is no beauty that is attractive without happiness." },     
 {  "categ" :"Confidence", "mynum" :"18",  "mysource" :"Brene Brown", "myquote"  :"You either walk inside your story and own it or you stand outside your story and hustle for your worthiness." },     
 {  "categ" :"Confidence", "mynum" :"19",  "mysource" :"Bryce Courtenay", "myquote"  :"Pride is holding your head up when everyone around you has theirs bowed. Courage is what makes you do it" },     
 {  "categ" :"Confidence", "mynum" :"20",  "mysource" :"Rosalyn Smith Carter", "myquote"  :"If you doubt you can accomplish something, then you can't accomplish it. You have to have confidence in your ability, and then be tough enough to follow through." },     
 {  "categ" :"Confidence", "mynum" :"21",  "mysource" :"Author Unknown", "myquote"  :"The best way to gain self-confidence is to do what you are afraid to do." },     
 {  "categ" :"Confidence", "mynum" :"22",  "mysource" :"Malcolm Forbes", "myquote"  :"Too many people overvalue what they are not, and undervalue what they are." },     
 {  "categ" :"Confidence", "mynum" :"23",  "mysource" :"Johann Wolfgang von Goethe", "myquote"  :"As soon as you trust yourself, you will know how to live." },     
 {  "categ" :"Confidence", "mynum" :"24",  "mysource" :"Willie Nelson", "myquote"  :"When I started counting my blessings, my whole life turned around." },     
 {  "categ" :"Confidence", "mynum" :"25",  "mysource" :"W.C. Fields", "myquote"  :"It ain't what they call you, it's what you answer to." },     
 {  "categ" :"Confidence", "mynum" :"26",  "mysource" :"Dr. Benjamin Spock", "myquote"  :"Trust yourself. You know more than you think you do." },     
 {  "categ" :"Confidence", "mynum" :"27",  "mysource" :"Dr. Seuss", "myquote"  :"You have brains in your head. You have feet in your shoes. You can steer yourself in any direction you choose. You're on your own. And you know what you know. You are the guy who'll decide where to go." },     
 {  "categ" :"Confidence", "mynum" :"28",  "mysource" :"T. Harv Eker", "myquote"  :"Successful people have fear, successful people have doubts, and successful people have worries. They just don't let these feelings stop them." },     
 {  "categ" :"Confidence", "mynum" :"29",  "mysource" :"James Cameron", "myquote"  :"But failure has to be an option in art and in exploration - because it's a leap of faith. And no important endeavor that required innovation was done without risk. You have to be willing to take those risks" },     
 {  "categ" :"Confidence", "mynum" :"30",  "mysource" :"Wayne Dyer", "myquote"  :"You cannot be lonely if you like the person you're alone with." },     
 {  "categ" :"Confidence", "mynum" :"31",  "mysource" :"Johann Wolfgang von Goethe", "myquote"  :"As soon as you trust yourself, you will know how to live." },     
 {  "categ" :"Confidence", "mynum" :"32",  "mysource" :"Gloria Gaynor", "myquote"  :"Well, we all know that self-esteem comes from what you think of you, not what other people think of you." },     
 {  "categ" :"Confidence", "mynum" :"33",  "mysource" :" Pirke Avoth", "myquote"  :"If I am not for myself, who will be?" },     
 {  "categ" :"Confidence", "mynum" :"34",  "mysource" :"Franklin D. Roosevelt", "myquote"  :"Confidence ... thrives on honesty, on honor, on the sacredness of obligations, on faithful protection and on unselfish performance. Without them it cannot live." },     
 {  "categ" :"Confidence", "mynum" :"35",  "mysource" :"Lou Holtz", "myquote"  :"You were not born a winner, and you were not born a loser. You are what you make yourself be." },     
 {  "categ" :"Confidence", "mynum" :"36",  "mysource" :"Mark Twain", "myquote"  :"Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbour. Catch the trade winds in your sail. Explore. Dream. Discover." },     
 {  "categ" :"Confidence", "mynum" :"37",  "mysource" :"Goldie Hawn", "myquote"  :"I've finally stopped running away from myself. Who else is there better to be?" },     
 {  "categ" :"Confidence", "mynum" :"38",  "mysource" :"Eleanor Roosevelt", "myquote"  :"What could we accomplish if we knew we could not fail?" },     
 {  "categ" :"Confidence", "mynum" :"39",  "mysource" :"Brian Tracy", "myquote"  :"Confidence is a habit that can be developed by acting as if you already had the confidence you desire to have." },     
 {  "categ" :"Confidence", "mynum" :"40",  "mysource" :"Alan Cohen", "myquote"  :"Wouldn't it be powerful if you fell in love with yourself so deeply that you would do just about anything if you knew it would make you happy? This is precisely how much life loves you and wants you to nurture yourself. The deeper you love yourself, the more the universe will affirm your worth. Then you can enjoy a lifelong love affair that brings you the richest fulfillment from inside out." },     
 {  "categ" :"Confidence", "mynum" :"41",  "mysource" :"Eleanor Roosevelt", "myquote"  :"You wouldn't worry so much about what others think of you if you realized how seldom they do." },     
 {  "categ" :"Confidence", "mynum" :"42",  "mysource" :"Buddha", "myquote"  :"You yourself, as much as anybody in the entire universe, deserve your love and affection." },     
 {  "categ" :"Confidence", "mynum" :"43",  "mysource" :"Erica Jong", "myquote"  :"I have gone ahead despite the pounding in the heart that says 'Turn Back'." },     
 {  "categ" :"Confidence", "mynum" :"44",  "mysource" :"Henry David Thoreau", "myquote"  :"What a man thinks of himself, that it is which determines, or rather indicates his fate." },     
 {  "categ" :"Confidence", "mynum" :"45",  "mysource" :"Dennis Waitley.", "myquote"  :"The most important key to the permanent enhancement of esteem is the practice of positive inner-talk." },     
 {  "categ" :"Confidence", "mynum" :"46",  "mysource" :"Andrae Dubus", "myquote"  :"Shyness has a strange element of narcissism, a belief that how we look, how we perform, is truly important to other people." },     
 {  "categ" :"Confidence", "mynum" :"47",  "mysource" :"Michelle Obama", "myquote"  :"Whether you come from a council estate or a country estate, your success will be determined by your own confidence and fortitude." },     
 {  "categ" :"Confidence", "mynum" :"48",  "mysource" :"Thomas Alva Edison", "myquote"  :"If we all did the things we are capable of doing, we would literally astound ourselves." },     
 {  "categ" :"Confidence", "mynum" :"49",  "mysource" :"Elisabeth Kubler-Ross", "myquote"  :"People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in their true beauty is revealed only if there is light from within." },     
 {  "categ" :"Confidence", "mynum" :"50",  "mysource" :"Bobbe Sommer", "myquote"  :"Having a low opinion of yourself is not 'modesty'. It's self-destruction. Holding your uniqueness in high regard is not 'egotism'. It's a necessary precondition to happiness and success." },     
 {  "categ" :"Confidence", "mynum" :"51",  "mysource" :"Les Brown", "myquote"  :"You are blessed and highly favored." },     
 {  "categ" :"Confidence", "mynum" :"52",  "mysource" :"Iris Apfel", "myquote"  :"I say, dress to please yourself. Listen to your inner muse and take a chance. Wear something that says 'Here I am!' today." },     
 {  "categ" :"Confidence", "mynum" :"53",  "mysource" :"Thomas Jefferson", "myquote"  :"Nothing can stop the man with the right mental attitude from achieving his goal.  Nothing on earth can help the man with the wrong mental attitude." },     
 {  "categ" :"Confidence", "mynum" :"54",  "mysource" :"Author Unknown", "myquote"  :"Always act like you're wearing an invisible crown." },     
 {  "categ" :"Confidence", "mynum" :"55",  "mysource" :"Author Unknown", "myquote"  :"If you really put a small value upon yourself, rest assured that the world will not raise your price." },     
 {  "categ" :"Confidence", "mynum" :"56",  "mysource" :"Alan Cohen", "myquote"  :"To love yourself right now, just as you are, is to give yourself heaven. Don't wait until you die. If you wait, you die now. If you love, you live now." },     
 {  "categ" :"Confidence", "mynum" :"57",  "mysource" :"Robert Collier", "myquote"  :"Your chances of success in any undertaking can always be measured by your belief in yourself." },     
 {  "categ" :"Confidence", "mynum" :"58",  "mysource" :"Steve Maraboli", "myquote"  :"Embracing your true self radiates a natural beauty that cannot be diluted or ignored. Confident, powerful, untamable, badass you!" },     
 {  "categ" :"Confidence", "mynum" :"59",  "mysource" :"Mary Kay Ash", "myquote"  :"Aerodynamically the bumblebee shouldn't be able to fly, but the bumblebee doesn't know that so it goes on flying anyway." },     
 {  "categ" :"Confidence", "mynum" :"60",  "mysource" :" J.M. Barrie ~ Peter Pan", "myquote"  :"The moment you doubt whether you can fly, you cease forever to be able to do it." },     
 {  "categ" :"Confidence", "mynum" :"61",  "mysource" :"Judy Garland", "myquote"  :"Always be a first-rate version of yourself, instead of a second-rate version of somebody else." },     
 {  "categ" :"Confidence", "mynum" :"62",  "mysource" :"Coco Chanel", "myquote"  :"In order to be irreplaceable one must always be different." },     
 {  "categ" :"Confidence", "mynum" :"63",  "mysource" :"E. E. Cummings", "myquote"  :"Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit." },     
 {  "categ" :"Confidence", "mynum" :"64",  "mysource" :"Louise L. Hay.", "myquote"  :"Love is the great miracle cure. Loving ourselves works miracles in our lives." },     
 {  "categ" :"Confidence", "mynum" :"65",  "mysource" :"Rumi", "myquote"  :"Don't be satisfied with stories, how things have gone with others. Unfold your own myth." },     
 {  "categ" :"Confidence", "mynum" :"66",  "mysource" :"Buckminster Fuller", "myquote"  :"I am convinced all of humanity is born with more gifts than we know. Most are born geniuses and just get de-geniused rapidly." },     
 {  "categ" :"Confidence", "mynum" :"67",  "mysource" :"Hayley Williams", "myquote"  :"To anyone that ever told you you're no good ... They're no better." },     
 {  "categ" :"Confidence", "mynum" :"68",  "mysource" :"Jeffrey I. Moore", "myquote"  :"Love yourself and love those around you. Take care of yourself and take care of those around you. Lead by example. Give love. Be a part of everything that is great in the world, and in turn there is more love and greatness in the world! Change the world!" },     
 {  "categ" :"Confidence", "mynum" :"69",  "mysource" :"Paul Tillich", "myquote"  :"The courage to be is the courage to accept oneself, in spite of being unacceptable." },     
 {  "categ" :"Confidence", "mynum" :"70",  "mysource" :"Les Brown", "myquote"  :"Someone else's opinion of you does not have to become your reality." },     
 {  "categ" :"Confidence", "mynum" :"71",  "mysource" :"Christopher Robin ~ Winnie the Pooh", "myquote"  :"Always remember you are braver than you believe, stronger than you seem, and smarter than you think." },     
 {  "categ" :"Confidence", "mynum" :"72",  "mysource" :"Nathaniel Branden", "myquote"  :"There is overwhelming evidence that the higher the level of self-esteem, the more likely one will be to treat others with respect, kindness, and generosity." },     
 {  "categ" :"Confidence", "mynum" :"73",  "mysource" :"Ben Sweet", "myquote"  :"The greatest success is successful self-acceptance." },     
 {  "categ" :"Confidence", "mynum" :"74",  "mysource" :"Oprah Winfrey", "myquote"  :"It is confidence in our bodies, minds, and spirits that allows us to keep looking for new adventures." },     
 {  "categ" :"Confidence", "mynum" :"75",  "mysource" :"Henry David Thoreau", "myquote"  :"Go confidently in the direction of your dreams and live the life you have imagined." },     
 {  "categ" :"Confidence", "mynum" :"76",  "mysource" :"Vincent Van Gogh", "myquote"  :"If you hear a voice within you say 'you cannot paint', then by all means paint, and that voice will be silenced." },     
 {  "categ" :"Confidence", "mynum" :"77",  "mysource" :"Marie Curie", "myquote"  :"Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something and that this thing must be attained." },     
 {  "categ" :"Confidence", "mynum" :"78",  "mysource" :"Tim Gunn", "myquote"  :"You have no control over other people's taste, so focus on staying true to your own." },     
 {  "categ" :"Confidence", "mynum" :"79",  "mysource" :"Richard Bach", "myquote"  :"Argue for your limitations and, sure enough, they're yours." },     
 {  "categ" :"Confidence", "mynum" :"80",  "mysource" :"Roderick Thorp", "myquote"  :"We have to learn to be our own best friends because we fall too easily into the trap of being our own worst enemies." },     
 {  "categ" :"Confidence", "mynum" :"81",  "mysource" :"Bruce Lee", "myquote"  :"Always be yourself and have faith in yourself. Do not go out and look for a successful personality and try to duplicate it." },     
 {  "categ" :"Confidence", "mynum" :"82",  "mysource" :"Helen Keller", "myquote"  :"Never bend your head. Hold it high. Look the world straight in the eye." },     
 {  "categ" :"Confidence", "mynum" :"83",  "mysource" :"Peter T. Mcintyre", "myquote"  :"Confidence comes not from always being right but from not fearing to be wrong." },     
 {  "categ" :"Confidence", "mynum" :"84",  "mysource" :"Jim Rohn", "myquote"  :"To have an incredible increase in self esteem, all you have to do is start doing some little something. You don't have to do spectacularly dramatic things for self esteem to start going off the scale. Just make a commitment to any easy discipline. Then another one and another one." },     
 {  "categ" :"Confidence", "mynum" :"85",  "mysource" :"Unknown Author", "myquote"  :"The most important opinion you have is the one you have of yourself, and the most significant things you say all day are those things you say to yourself." },     
 {  "categ" :"Confidence", "mynum" :"86",  "mysource" :"Jerry Gillies", "myquote"  :"The strongest single factor in prosperity consciousness is self-esteem: believing you can do it, believing you deserve it, believing you will get it." },     
 {  "categ" :"Confidence", "mynum" :"87",  "mysource" :"Hafiz", "myquote"  :"I wish I could show you, when you are lonely or in darkness, the astonishing light of your own being." },     
 {  "categ" :"Confidence", "mynum" :"88",  "mysource" :"Queen Latifah", "myquote"  :"I had to grow to love my body. I did not have a good self-image at first. Finally it occurred to me, I'm either going to love me or hate me. And I chose to love myself. Then everything kind of sprung from there. Things that I thought weren't attractive became sexy. Confidence makes you sexy." },     
 {  "categ" :"Confidence", "mynum" :"89",  "mysource" :"Jodi Picoult", "myquote"  :"When you're different, sometimes you don't see the millions of people who accept you for what you are. All you notice is the person who doesn't." },     
 {  "categ" :"Confidence", "mynum" :"90",  "mysource" :"Barrie Davenport", "myquote"  :"Low self-confidence isn't a life sentence. Self-confidence can be learned, practiced, and mastered - just like any other skill. Once you master it, everything in your life will change for the better." },     
 {  "categ" :"Confidence", "mynum" :"91",  "mysource" :"Marianne Williamson", "myquote"  :"Our deepest fear is not that we are inadequate.  Our deepest fear is that we are powerful beyond measure.  It is our light, not our darkness that most frightens us.  We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous?  Actually, who are you not to be?" },     
 {  "categ" :"Confidence", "mynum" :"92",  "mysource" :"Oprah Winfrey", "myquote"  :"Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness." },     
 {  "categ" :"Confidence", "mynum" :"93",  "mysource" :"Mark Victor Hansen ", "myquote"  :"Don't wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident and more and more successful." },     
 {  "categ" :"Confidence", "mynum" :"94",  "mysource" :"Norman Vincent Peale", "myquote"  :"Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy." },     
 {  "categ" :"Confidence", "mynum" :"95",  "mysource" :"Dr. Sonya Friedman", "myquote"  :"The way you treat yourself sets the standard for others." },     
 {  "categ" :"Confidence", "mynum" :"96",  "mysource" :"Robert Downey, Jr.", "myquote"  :"I think that the power is the principle. The principle of moving forward, as though you have the confidence to move forward, eventually gives you confidence when you look back and see what you've done." },     
 {  "categ" :"Confidence", "mynum" :"97",  "mysource" :"Tina Fey", "myquote"  :"Don't waste your energy trying to change opinions ... do your thing, and don't care if they like it." },     
 {  "categ" :"Confidence", "mynum" :"98",  "mysource" :"Arthur Ashe ", "myquote"  :"One important key to success is self-confidence. An important key to self-confidence is preparation." },     
 {  "categ" :"Confidence", "mynum" :"99",  "mysource" :"Golda Meir ", "myquote"  :"Trust yourself. Create the kind of self that you will be happy to live with all your life. Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement." },     
 {  "categ" :"Confidence", "mynum" :"100",  "mysource" :"Dr. Seuss", "myquote"  :"Today you are you, that is truer than true. There is no one alive who is youer than you." },     
 {  "categ" :"Confidence", "mynum" :"101",  "mysource" :"Sir Edmund Hillary", "myquote"  :"It is not the mountain we conquer, but ourselves." },     
 {  "categ" :"Confidence", "mynum" :"102",  "mysource" :"Marcus Garvey", "myquote"  :"With confidence, you have won before you have started." },     
 {  "categ" :"Confidence", "mynum" :"103",  "mysource" :"Nathaniel Branden", "myquote"  :"To trust one's mind and to know that one is worthy of happiness is the essence of self-esteem." },     
 {  "categ" :"Confidence", "mynum" :"104",  "mysource" :"Nathaniel Branden", "myquote"  :"Persons of high self esteem are not driven to make themselves superior to others. They do not seek to prove their value by measuring themselves against a comparative standard. Their joy is being who they are, not in being better than someone else." },     
 {  "categ" :"Confidence", "mynum" :"105",  "mysource" :"Barrie Davenport", "myquote"  :"True beauty is the flame of self-confidence that shines from the inside out." },     
 {  "categ" :"Confidence", "mynum" :"106",  "mysource" :"Avril Lavigne", "myquote"  :"Why should I care what other people think of me? I am who I am. And who I wanna be." },     
 {  "categ" :"Confidence", "mynum" :"107",  "mysource" :"Paulo Coelho ~ The Alchemist", "myquote"  :"Remember that wherever your heart is, there you will find your treasure." },     
 {  "categ" :"Confidence", "mynum" :"108",  "mysource" :"Ralph Waldo Emerson", "myquote"  :"Self-trust is the first secret of success." },     
 {  "categ" :"Confidence", "mynum" :"109",  "mysource" :"Brene Brown", "myquote"  :"Talk to yourself like you would to someone you love." },     
 {  "categ" :"Confidence", "mynum" :"110",  "mysource" :"Oscar Wilde", "myquote"  :"To love oneself is the beginning of a life-long romance." },     
 {  "categ" :"Confidence", "mynum" :"111",  "mysource" :"Henry Ford", "myquote"  :"Whether you think you can or think you can't â€“ you are right." },     
 {  "categ" :"Confidence", "mynum" :"112",  "mysource" :"Bruce Barton", "myquote"  :"Nothing splendid has ever been achieved except by those who dared believe that something inside of them was superior to circumstance." },     
 {  "categ" :"Confidence", "mynum" :"113",  "mysource" :"Laozi", "myquote"  :"Because one believes in oneself, one doesn't try to convince. Because one is content with oneself, one doesn't need others' approval. Because one accepts oneself, the whole world accepts him or her." },     
 {  "categ" :"Confidence", "mynum" :"114",  "mysource" :"Dr. Robert Anthony", "myquote"  :"You can have anything you want if you are willing to give up the belief that you can't have it." },     
 {  "categ" :"Confidence", "mynum" :"115",  "mysource" :"Brian Tracy", "myquote"  :"You have within you right now, everything you need to deal with whatever the world can throw at you." },     
 {  "categ" :"Confidence", "mynum" :"116",  "mysource" :"Nathaniel Branden.", "myquote"  :"One of the most significant characteristics of healthy esteem is that it is the state of one who is not at war either with himself or with others." },     
 {  "categ" :"Confidence", "mynum" :"117",  "mysource" :"Anna Freud", "myquote"  :"I was always looking outside myself for strength and confidence but it comes from within. It is there all the time." },     
 {  "categ" :"Confidence", "mynum" :"118",  "mysource" :"Dr. Nathaniel Branden", "myquote"  :"The tragedy is that so many people look for self-confidence and self-respect everywhere except within themselves, and so they fail in their search." },     
 {  "categ" :"Confidence", "mynum" :"119",  "mysource" :"Elizabeth Taylor", "myquote"  :"I don't entirely approve of some of the things I have done, or am, or have been. But I'm me. God knows, I'm me." },     
 { "categ" :"Confidence", "mynum" :"120",  "mysource" :"Mark Twain", "myquote"  :"Thousands of geniuses live and die undiscovered either by themselves or by others." }, 
 {  "categ" :"Leadership", "mynum" :"1",  "mysource" :"Abraham Lincoln", "myquote"  :"Listen! No man is good enough to govern another man without that other's consent." }, 
 {  "categ" :"Leadership", "mynum" :"2",  "mysource" :"Abraham Lincoln", "myquote"  :"Whatever you are; be a good one!" }, 
 {  "categ" :"Leadership", "mynum" :"3",  "mysource" :"Andre Malraux", "myquote"  :"To command is to serve, nothing more and nothing less." }, 
 {  "categ" :"Leadership", "mynum" :"4",  "mysource" :"Andrew Carnegie", "myquote"  :"No man will make a great leader who wants to do it all himself, or to get all the credit for doing it." }, 
 {  "categ" :"Leadership", "mynum" :"5",  "mysource" :"Aristotle", "myquote"  :"He who has never learned to obey cannot be a good commander." }, 
 {  "categ" :"Leadership", "mynum" :"6",  "mysource" :"Arnold Glasow", "myquote"  :"One of the tests of leadership is the ability to recognize a problem before it becomes an emergency." }, 
 {  "categ" :"Leadership", "mynum" :"7",  "mysource" :"Benjamin Disraeli", "myquote"  :"I must follow the people. Am I not their leader?" }, 
 {  "categ" :"Leadership", "mynum" :"8",  "mysource" :"Benjamin Franklin", "myquote"  :"If you would not be forgotten, as soon as you are dead and rotten, either write things worth reading, or do things worth the writing." }, 
 {  "categ" :"Leadership", "mynum" :"9",  "mysource" :"Bill Bradley", "myquote"  :"Leadership is unlocking people's potential to become better." }, 
 {  "categ" :"Leadership", "mynum" :"10",  "mysource" :"Bill Gates", "myquote"  :"As we look ahead into the next century, leaders will be those who empower others." }, 
 {  "categ" :"Leadership", "mynum" :"11",  "mysource" :"Bill Owens", "myquote"  :"True leadership lies in guiding others to success. In ensuring that everyone is performing at their best, doing the work they are pledged to do and doing it well." }, 
 {  "categ" :"Leadership", "mynum" :"12",  "mysource" :"Brian Tracy", "myquote"  :"Become the kind of leader that people would follow voluntarily; even if you had no title or position." }, 
 {  "categ" :"Leadership", "mynum" :"13",  "mysource" :"Brian Tracy", "myquote"  :"Leaders think and talk about the solutions. Followers think and talk about the problems." }, 
 {  "categ" :"Leadership", "mynum" :"14",  "mysource" :"Chinese Proverb", "myquote"  :"Not the cry, but the flight of a wild duck, leads the flock to fly and follow." }, 
 {  "categ" :"Leadership", "mynum" :"15",  "mysource" :"Colin Powell", "myquote"  :"Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership." }, 
 {  "categ" :"Leadership", "mynum" :"16",  "mysource" :"Dee Dee Myers", "myquote"  :"I am endlessly fascinated that playing football is considered a training ground for leadership, but raising children isn't." }, 
 {  "categ" :"Leadership", "mynum" :"17",  "mysource" :"Donald Rumsfeld", "myquote"  :"Don't necessarily avoid sharp edges. Occasionally they are necessary to leadership." }, 
 {  "categ" :"Leadership", "mynum" :"18",  "mysource" :"Douglas MacArthur", "myquote"  :"A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent." }, 
 {  "categ" :"Leadership", "mynum" :"19",  "mysource" :"Dwight Eisenhower", "myquote"  :"The supreme quality of leadership is integrity." }, 
 {  "categ" :"Leadership", "mynum" :"20",  "mysource" :"Dwight Eisenhower", "myquote"  :"You don't lead by hitting people over the head – that's assault, not leadership." }, 
 {  "categ" :"Leadership", "mynum" :"21",  "mysource" :"Eleanor Roosevelt", "myquote"  :"Do what you feel in your heart to be right–for you'll be criticized anyway." }, 
 {  "categ" :"Leadership", "mynum" :"22",  "mysource" :"Eleanor Roosevelt", "myquote"  :"You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do." }, 
 {  "categ" :"Leadership", "mynum" :"23",  "mysource" :"Eric Hoffer", "myquote"  :"The leader has to be practical and a realist yet must talk the language of the visionary and the idealist." }, 
 {  "categ" :"Leadership", "mynum" :"24",  "mysource" :"Erskine Bowles", "myquote"  :"Leadership is the key to 99 percent of all successful efforts." }, 
 {  "categ" :"Leadership", "mynum" :"25",  "mysource" :"Friedrich Nietzsche", "myquote"  :"To do great things is difficult; but to command great things is more difficult." }, 
 {  "categ" :"Leadership", "mynum" :"26",  "mysource" :"Fuchan Yuan", "myquote"  :"There are three essentials to leadership: humility, clarity and courage." }, 
 {  "categ" :"Leadership", "mynum" :"27",  "mysource" :"General Colin Powell", "myquote"  :"Great leaders are almost always great simplifiers, who can cut through argument, debate, and doubt to offer a solution everybody can understand." }, 
 {  "categ" :"Leadership", "mynum" :"28",  "mysource" :"General Douglas MacArthur", "myquote"  :"Never give an order that can't be obeyed." }, 
 {  "categ" :"Leadership", "mynum" :"29",  "mysource" :"General Dwight Eisenhower", "myquote"  :"Leadership is the art of getting someone else to do something you want done because he wants to do it." }, 
 {  "categ" :"Leadership", "mynum" :"30",  "mysource" :"General George Patton", "myquote"  :"Lead me, follow me, or get out of my way." }, 
 {  "categ" :"Leadership", "mynum" :"31",  "mysource" :"General George Patton", "myquote"  :"Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity." }, 
 {  "categ" :"Leadership", "mynum" :"32",  "mysource" :"General Montgomery", "myquote"  :"My own definition of leadership is this: The capacity and the will to rally men and women to a common purpose and the character which inspires confidence." }, 
 {  "categ" :"Leadership", "mynum" :"33",  "mysource" :"George Patton", "myquote"  :"A good plan violently executed now is better than a perfect plan executed next week." }, 
 {  "categ" :"Leadership", "mynum" :"34",  "mysource" :"Harry S. Truman", "myquote"  :"Men make history and not the other way around. In periods where there is no leadership, society stands still. Progress occurs when courageous, skillful leaders seize the opportunity to change things for the better." }, 
 {  "categ" :"Leadership", "mynum" :"35",  "mysource" :"Harvey Firestone", "myquote"  :"The growth and development of people is the highest calling of leadership." }, 
 {  "categ" :"Leadership", "mynum" :"36",  "mysource" :"Herbert Swope", "myquote"  :"I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody." }, 
 {  "categ" :"Leadership", "mynum" :"37",  "mysource" :"Jack Welch", "myquote"  :"Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others." }, 
 {  "categ" :"Leadership", "mynum" :"38",  "mysource" :"Jesse Jackson", "myquote"  :"Leadership cannot just go along to get along. Leadership must meet the moral challenge of the day." }, 
 {  "categ" :"Leadership", "mynum" :"39",  "mysource" :"Jim Rohn", "myquote"  :"The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy; be humble, but not timid; be proud, but not arrogant; have humor, but without folly." }, 
 {  "categ" :"Leadership", "mynum" :"40",  "mysource" :"Johann Wolfgang Von Goethe", "myquote"  :"A great person attracts great people and knows how to hold them together." }, 
 {  "categ" :"Leadership", "mynum" :"41",  "mysource" :"John C. Maxwell", "myquote"  :"Leaders must be close enough to relate to others, but far enough ahead to motivate them." }, 
 {  "categ" :"Leadership", "mynum" :"42",  "mysource" :"John C. Maxwell", "myquote"  :"Leadership is influence." }, 
 {  "categ" :"Leadership", "mynum" :"43",  "mysource" :"John F. Kennedy", "myquote"  :"Leadership and learning are indispensable to each other." }, 
 {  "categ" :"Leadership", "mynum" :"44",  "mysource" :"John J Pershing", "myquote"  :"A competent leader can get efficient service from poor troops, while on the contrary an incapable leader can demoralize the best of troops." }, 
 {  "categ" :"Leadership", "mynum" :"45",  "mysource" :"John Kenneth Galbraith", "myquote"  :"All of the great leaders have had one characteristic in common: it was the willingness to confront unequivocally the major anxiety of their people in their time. This, and not much else, is the essence of leadership." }, 
 {  "categ" :"Leadership", "mynum" :"46",  "mysource" :"John Maxwell", "myquote"  :"A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit." }, 
 {  "categ" :"Leadership", "mynum" :"47",  "mysource" :"John Maxwell", "myquote"  :"A great leader's courage to fulfill his vision comes from passion, not position." }, 
 {  "categ" :"Leadership", "mynum" :"48",  "mysource" :"John Maxwell", "myquote"  :"A leader is one who knows the way, goes the way, and shows the way." }, 
 {  "categ" :"Leadership", "mynum" :"49",  "mysource" :"John Maxwell", "myquote"  :"People buy into the leader before they buy into the vision." }, 
 {  "categ" :"Leadership", "mynum" :"50",  "mysource" :"John Quincy Adams", "myquote"  :"If your actions inspire others to dream more, learn more, do more and become more, you are a leader." }, 
 {  "categ" :"Leadership", "mynum" :"51",  "mysource" :"John Zenger", "myquote"  :"Great leaders are not defined by the absence of weakness, but rather by the presence of clear strengths." }, 
 {  "categ" :"Leadership", "mynum" :"52",  "mysource" :"Ken Blanchard", "myquote"  :"The greatest leaders mobilize others by coalescing people around a shared vision." }, 
 {  "categ" :"Leadership", "mynum" :"53",  "mysource" :"Ken Kesey", "myquote"  :"You don't lead by pointing and telling people some place to go. You lead by going to that place and making a case." }, 
 {  "categ" :"Leadership", "mynum" :"54",  "mysource" :"Kenneth Blanchard", "myquote"  :"The key to successful leadership today is influence, not authority." }, 
 {  "categ" :"Leadership", "mynum" :"55",  "mysource" :"Lao Tzu", "myquote"  :"A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves" }, 
 {  "categ" :"Leadership", "mynum" :"56",  "mysource" :"Latin Proverb", "myquote"  :"It is absurd that a man should rule others, who cannot rule himself." }, 
 {  "categ" :"Leadership", "mynum" :"57",  "mysource" :"Marco Rubio", "myquote"  :"We live in a society obsessed with public opinion. But leadership has never been about popularity." }, 
 {  "categ" :"Leadership", "mynum" :"58",  "mysource" :"Margaret Mead", "myquote"  :"Never doubt that a small group of thoughtful, concerned citizens can change world. Indeed it is the only thing that ever has." }, 
 {  "categ" :"Leadership", "mynum" :"59",  "mysource" :"Max DePree", "myquote"  :"The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant." }, 
 {  "categ" :"Leadership", "mynum" :"60",  "mysource" :"Max Lucado", "myquote"  :"A man who wants to lead the orchestra must turn his back on the crowd." }, 
 {  "categ" :"Leadership", "mynum" :"61",  "mysource" :"Maya Angelou", "myquote"  :"If one is lucky, a solitary fantasy can totally transform one million realities." }, 
 {  "categ" :"Leadership", "mynum" :"62",  "mysource" :"Michael Jordan", "myquote"  :"Earn your leadership every day." }, 
 {  "categ" :"Leadership", "mynum" :"63",  "mysource" :"Multiple Attributions", "myquote"  :"You don't need a title to be a leader." }, 
 {  "categ" :"Leadership", "mynum" :"64",  "mysource" :"Napoleon Bonaparte", "myquote"  :"A leader is a dealer in hope." }, 
 {  "categ" :"Leadership", "mynum" :"65",  "mysource" :"Napoleon Bonaparte", "myquote"  :"When I give a minister an order, I leave it to him to find the means to carry it out." }, 
 {  "categ" :"Leadership", "mynum" :"66",  "mysource" :"Nelson Mandela", "myquote"  :"It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership." }, 
 {  "categ" :"Leadership", "mynum" :"67",  "mysource" :"Norman Schwarzkopf", "myquote"  :"Leadership is a potent combination of strategy and character. But if you must be without one, be without the strategy." }, 
 {  "categ" :"Leadership", "mynum" :"68",  "mysource" :"Ovid", "myquote"  :"A ruler should be slow to punish and swift to reward." }, 
 {  "categ" :"Leadership", "mynum" :"69",  "mysource" :"Pat Riley", "myquote"  :"To have long term success as a coach or in any position of leadership, you have to be obsessed in some way." }, 
 {  "categ" :"Leadership", "mynum" :"70",  "mysource" :"Peter Drucker", "myquote"  :"Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes." }, 
 {  "categ" :"Leadership", "mynum" :"71",  "mysource" :"Peter Drucker", "myquote"  :"Leadership is lifting a person's vision to high sights, the raising of a person's performance to a higher standard, the building of a personality beyond its normal limitations." }, 
 {  "categ" :"Leadership", "mynum" :"72",  "mysource" :"Peter Drucker", "myquote"  :"So much of what we call management consists in making it difficult for people to work." }, 
 {  "categ" :"Leadership", "mynum" :"73",  "mysource" :"Polybius", "myquote"  :"A good general not only sees the way to victory; he also knows when victory is impossible." }, 
 {  "categ" :"Leadership", "mynum" :"74",  "mysource" :"Proverbs 29:18", "myquote"  :"Where there is no vision, the people perish." }, 
 {  "categ" :"Leadership", "mynum" :"75",  "mysource" :"Publilius Syrus", "myquote"  :"Anyone can hold the helm when the sea is calm." }, 
 {  "categ" :"Leadership", "mynum" :"76",  "mysource" :"Ralph Nader", "myquote"  :"I start with the premise that the function of leadership is to produce more leaders, not more followers." }, 
 {  "categ" :"Leadership", "mynum" :"77",  "mysource" :"Rear Admiral Grace Murray Hopper", "myquote"  :"You manage things; you lead people." }, 
 {  "categ" :"Leadership", "mynum" :"78",  "mysource" :"Reverend Theodore Hesburgh", "myquote"  :"The very essence of leadership is that you have to have a vision. It's got to be a vision you articulate clearly and forcefully on every occasion. You can't blow an uncertain trumpet." }, 
 {  "categ" :"Leadership", "mynum" :"79",  "mysource" :"Rosalynn Carter", "myquote"  :"A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go, but ought to be." }, 
 {  "categ" :"Leadership", "mynum" :"80",  "mysource" :"Ross Perot", "myquote"  :"Lead and inspire people. Don't try to manage and manipulate people. Inventories can be managed but people must be lead." }, 
 {  "categ" :"Leadership", "mynum" :"81",  "mysource" :"Sam Walton", "myquote"  :"Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish." }, 
 {  "categ" :"Leadership", "mynum" :"82",  "mysource" :"Seneca", "myquote"  :"He who has great power should use it lightly." }, 
 {  "categ" :"Leadership", "mynum" :"83",  "mysource" :"Sir Winston Churchill", "myquote"  :"The nation will find it very hard to look up to the leaders who are keeping their ears to the ground." }, 
 {  "categ" :"Leadership", "mynum" :"84",  "mysource" :"Solon", "myquote"  :"He who has learned how to obey will know how to command." }, 
 {  "categ" :"Leadership", "mynum" :"85",  "mysource" :"Stephen Covey", "myquote"  :"Effective leadership is putting first things first. Effective management is discipline, carrying it out." }, 
 {  "categ" :"Leadership", "mynum" :"86",  "mysource" :"Stephen Covey", "myquote"  :"Management is efficiency in climbing the ladder of success; leadership determines whether the ladder is leaning against the right wall." }, 
 {  "categ" :"Leadership", "mynum" :"87",  "mysource" :"Stephen Covey", "myquote"  :"What you do has far greater impact than what you say." }, 
 {  "categ" :"Leadership", "mynum" :"88",  "mysource" :"Stephen King", "myquote"  :"A cowardly leader is the most dangerous of men." }, 
 {  "categ" :"Leadership", "mynum" :"89",  "mysource" :"Theodore Roosevelt", "myquote"  :"The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint enough to keep from meddling with them while they do it." }, 
 {  "categ" :"Leadership", "mynum" :"90",  "mysource" :"Thomas Jefferson", "myquote"  :"In matters of style, swim with the current; in matters of principle, stand like a rock." }, 
 {  "categ" :"Leadership", "mynum" :"91",  "mysource" :"Tom Peters", "myquote"  :"Management is about arranging and telling. Leadership is about nurturing and enhancing." }, 
 {  "categ" :"Leadership", "mynum" :"92",  "mysource" :"Tony Blair", "myquote"  :"The art of leadership is saying no, not saying yes. It is very easy to say yes." }, 
 {  "categ" :"Leadership", "mynum" :"93",  "mysource" :"Unknown", "myquote"  :"My responsibility is getting all my players playing for the name on the front of the jersey, not the one on the back." }, 
 {  "categ" :"Leadership", "mynum" :"94",  "mysource" :"Vince Lombardi", "myquote"  :"Leaders aren't born, they are made. And they are made just like anything else, through hard work. And that's the price we'll have to pay to achieve that goal, or any goal." }, 
 {  "categ" :"Leadership", "mynum" :"95",  "mysource" :"Walter Lippman", "myquote"  :"The final test of a leader is that he leaves behind him in other men, the conviction and the will to carry on." }, 
 {  "categ" :"Leadership", "mynum" :"96",  "mysource" :"Warren Bennis", "myquote"  :"I am reminded how hollow the label of leadership sometimes is and how heroic followership can be." }, 
 {  "categ" :"Leadership", "mynum" :"97",  "mysource" :"Warren Bennis", "myquote"  :"Leadership is the capacity to translate vision into reality." }, 
 {  "categ" :"Leadership", "mynum" :"98",  "mysource" :"Warren Bennis", "myquote"  :"The most dangerous leadership myth is that leaders are born-that there is a genetic factor to leadership. That's nonsense; in fact, the opposite is true. Leaders are made rather than born." }, 
 {  "categ" :"Leadership", "mynum" :"99",  "mysource" :"Wendell Willkie", "myquote"  :"Education is the mother of leadership." }, 
 {  "categ" :"Leadership", "mynum" :"100",  "mysource" :"Woodrow Wilson", "myquote"  :"Leadership does not always wear the harness of compromise." }
  ]; 

  // initialize filter object
  $scope.filter = {};

  // reset the filter
  $scope.resetFilter = function() {
    // set filter object as blank
    $scope.filter = {};
  };
});

